In [510]:
import numpy as np

In [511]:
lst = [1, 2, 3, 4, 5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [512]:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [513]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [514]:

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [515]:
np.zeros(3)

array([0., 0., 0.])

In [516]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [517]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [518]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [519]:
np.random.rand(2)

array([0.39986097, 0.04666566])

In [520]:
np.random.rand(4, 4)

array([[0.97375552, 0.23277134, 0.09060643, 0.61838601],
       [0.38246199, 0.98323089, 0.46676289, 0.85994041],
       [0.68030754, 0.45049925, 0.01326496, 0.94220176],
       [0.56328822, 0.3854165 , 0.01596625, 0.23089383]])

In [521]:
np.random.randn(4, 4)

array([[ 0.77919263, -1.10109776,  1.13022819,  0.37311891],
       [-0.38647295, -1.15877024,  0.56611283, -0.70445345],
       [-1.3779393 , -0.35311665, -0.46146572,  0.06665728],
       [-0.17628566,  1.20089277,  0.69839894, -0.17162884]])

In [522]:
np.random.randint(0, 9)

7

In [523]:
np.random.randint(0, 9, 3)

array([6, 8, 7], dtype=int32)

In [524]:
np.random.randint(0, 9, (4, 4))

array([[4, 1, 4, 7],
       [8, 8, 0, 8],
       [6, 8, 7, 0],
       [7, 7, 2, 0]], dtype=int32)

In [525]:
np.random.seed(1)
np.random.rand(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [526]:
arr = np.random.randint(0, 50, 25)
arr

array([37, 18, 20, 11, 42, 28, 29, 14,  4, 23, 23, 41, 49, 30, 32, 22, 13,
       41,  9,  7, 22,  1,  0, 17,  8], dtype=int32)

In [527]:
arr.shape

(25,)

In [528]:
arr.reshape(5, 5)

array([[37, 18, 20, 11, 42],
       [28, 29, 14,  4, 23],
       [23, 41, 49, 30, 32],
       [22, 13, 41,  9,  7],
       [22,  1,  0, 17,  8]], dtype=int32)

In [529]:
arr.max()

np.int32(49)

In [530]:
arr.argmax()

np.int64(12)

In [531]:
arr.min()

np.int32(0)

In [532]:
arr.argmin()

np.int64(22)

In [533]:
arr.dtype

dtype('int32')

In [534]:
arr2 = np.arange(1, 11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [535]:
arr2[7]

np.int64(8)

In [536]:
arr2[2:6]

array([3, 4, 5, 6])

In [537]:
arr2[:5]

array([1, 2, 3, 4, 5])

In [538]:
arr2[5:]

array([ 6,  7,  8,  9, 10])

In [539]:
arr2[0:5] = 10
arr2

array([10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [540]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [541]:
arr_2d.shape

(3, 3)

In [542]:
arr_2d[0]

array([ 5, 10, 15])

In [543]:
arr_2d[1, 1]

np.int64(25)

In [544]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [545]:
arr_2d[0:3, 1:3]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [546]:
arr3 = np.arange(0, 10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [547]:
bool_arr3 = arr3 > 4
bool_arr3

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [548]:
arr3[bool_arr3]

array([5, 6, 7, 8, 9])

In [549]:
arr3[bool_arr3==False]

array([0, 1, 2, 3, 4])

In [550]:
arr3[arr3 > 4]
# this is like [x for x in arr3 if x > 4]

array([5, 6, 7, 8, 9])

In [551]:
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [552]:
arr4 + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [553]:
arr4 - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [554]:
arr4 + arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [555]:
arr4 - arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [556]:
arr4 / arr4

C:\Users\santy\AppData\Local\Temp\ipykernel_23768\1071025465.py:1: RuntimeWarning: invalid value encountered in divide
  arr4 / arr4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [557]:
np.random.seed(42)

A = np.random.randint(0, 100, (4, 4))
B = np.random.randint(0, 100, (4, 4))

print(f"Matrix A :\n{A}\n")
print(f"Matrix B :\n{B}\n")

print(f"A + B:\n{A + B}\n")
print(f"A - B:\n{A - B}\n")
print(f"A * B:\n{A * B}\n")
print(f"A / B:\n{A / B}")

Matrix A :
[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]

Matrix B :
[[ 1 87 29 37]
 [ 1 63 59 20]
 [32 75 57 21]
 [88 48 90 58]]

A + B:
[[ 52 179  43 108]
 [ 61  83 141 106]
 [106 149 144 120]
 [111  50 111 110]]

A - B:
[[ 50   5 -15  34]
 [ 59 -43  23  66]
 [ 42  -1  30  78]
 [-65 -46 -69  -6]]

A * B:
[[  51 8004  406 2627]
 [  60 1260 4838 1720]
 [2368 5550 4959 2079]
 [2024   96 1890 3016]]

A / B:
[[5.10000000e+01 1.05747126e+00 4.82758621e-01 1.91891892e+00]
 [6.00000000e+01 3.17460317e-01 1.38983051e+00 4.30000000e+00]
 [2.31250000e+00 9.86666667e-01 1.52631579e+00 4.71428571e+00]
 [2.61363636e-01 4.16666667e-02 2.33333333e-01 8.96551724e-01]]


In [558]:
scalar = 3
mult_scalar = scalar * A

print(f"{scalar} * A:\n{mult_scalar}\n")

3 * A:
[[153 276  42 213]
 [180  60 246 258]
 [222 222 261 297]
 [ 69   6  63 156]]



In [559]:
transpose_A = A.T
print(f"A^(-1):\n{transpose_A}")

A^(-1):
[[51 60 74 23]
 [92 20 74  2]
 [14 82 87 21]
 [71 86 99 52]]


In [560]:
determinant = np.linalg.det(A)
print(f"|A| = {determinant}")

|A| = -1536879.9999999998


In [561]:
inverse_A = np.linalg.inv(A)
print(f"A^(-1):\n{inverse_A}")

A^(-1):
[[ 0.08570611  0.17686482 -0.15105929 -0.12193535]
 [-0.01338036 -0.04617407  0.04224403  0.01420801]
 [-0.03509448 -0.04471136  0.05526521  0.01664671]
 [-0.02322107 -0.05839623  0.04287127  0.06589454]]


In [562]:
np.dot(A, inverse_A)
print(f"A * A^(-1):\n{np.dot(A, inverse_A)}")

A * A^(-1):
[[ 1.00000000e+00  7.70217223e-16 -6.93889390e-16  3.33066907e-16]
 [-8.53483950e-16  1.00000000e+00 -2.05391260e-15 -2.22044605e-16]
 [-3.98986399e-16  1.18655086e-15  1.00000000e+00 -1.11022302e-16]
 [-1.80411242e-16  5.82867088e-16 -3.33066907e-16  1.00000000e+00]]


In [563]:
np.linalg.matrix_rank(A)
print(f"Rank of A: {np.linalg.matrix_rank(A)}")

Rank of A: 4


In [564]:
arr5 = np.arange(0, 10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [565]:
np.sqrt(arr5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [566]:
np.log(arr5)

C:\Users\santy\AppData\Local\Temp\ipykernel_23768\667223671.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr5)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [567]:
np.sin(arr5)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [568]:
arr5.sum()

np.int64(45)

In [569]:
arr5.mean()

np.float64(4.5)

In [570]:
arr5.max()

np.int64(9)

In [571]:
arr5.var()

np.float64(8.25)

In [572]:
arr.std()

np.float64(13.37723439280332)

In [573]:
arr_2d2 = np.arange(0, 30).reshape(5, 6)
arr_2d2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [574]:
arr_2d2.sum()

np.int64(435)

In [575]:
arr_2d2.sum(axis=0)

array([60, 65, 70, 75, 80, 85])

In [578]:
arr_2d2.sum(axis=1)

array([ 15,  51,  87, 123, 159])