In [637]:
import numpy as np

In [638]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [639]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [640]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [641]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [642]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [643]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [644]:
np.random.randint(0, 2)

1

In [645]:
np.random.randn(25)

array([-1.19847557,  0.10206972,  0.34497785,  1.46480619,  0.07487265,
       -1.38323031, -1.29387755, -0.73051405, -1.80124396, -0.46414402,
        0.00264574,  1.11150803, -0.98712541, -0.6649265 ,  0.02958994,
       -0.34135682,  0.58206788,  1.4676997 ,  0.0570415 , -0.10419663,
       -1.54580587,  0.46193421,  0.12165736,  0.48990154,  0.42367548])

In [646]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [647]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [648]:
M = np.arange(1, 26).reshape(5, 5)
M

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [649]:
M[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [650]:
M[3, 4]

np.int64(20)

In [651]:
M[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [652]:
M[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [653]:
M[4:][0]

array([21, 22, 23, 24, 25])

In [654]:
A = M[:4, :4]
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [655]:
B = M[1:, 1:]
B

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [656]:
A + B

array([[ 8, 10, 12, 14],
       [18, 20, 22, 24],
       [28, 30, 32, 34],
       [38, 40, 42, 44]])

In [657]:
A - B

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

In [658]:
A * B

array([[  7,  16,  27,  40],
       [ 72,  91, 112, 135],
       [187, 216, 247, 280],
       [352, 391, 432, 475]])

In [659]:
B.T

array([[ 7, 12, 17, 22],
       [ 8, 13, 18, 23],
       [ 9, 14, 19, 24],
       [10, 15, 20, 25]])

In [660]:
np.linalg.det(A)

np.float64(0.0)

In [661]:
try:
    np.linalg.inv(B)
except np.linalg.LinAlgError:
    print(f"La matriz B es singular y por lo tanto no tiene inversa ya que su determinante es {np.linalg.det(B)}")


La matriz B es singular y por lo tanto no tiene inversa ya que su determinante es 0.0


In [662]:
try:
    np.dot(A, np.linalg.inv(A))
except np.linalg.LinAlgError:
    print(f"La matriz A es singular por lo que no se puede hallar su matriz identidad, ya que esta operación depende de su inversa")


La matriz A es singular por lo que no se puede hallar su matriz identidad, ya que esta operación depende de su inversa


In [663]:
np.linalg.matrix_rank(B)

np.int64(2)